version: '3.4'
services:
  web:
    build: 
      context: .
      target: dev
    image: freqtradeorg/frequi:dev
    user: dev
    volumes:
      - ../:/home/dev/frequi
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - frequi
    ports:
      - 8080:8080

networks:
  frequi: