name: Freqtrade CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: npm install
      uses: jaid/action-npm-install@v1.2.1
      packageManager: npm

    - name: run lint
      run: |
        npm run lint

    # - name: Prettify code
    #   uses: creyD/prettier_action@v2.2
    #   with:
    #     dry: True
